### ISSUE TITLE
Doesn't work on Android 8 (O)

### ISSUE THREAD

**Issue by Over17** [Over17/UnityAndroidPermissions#4]
08-28 11:45:43.803: E/Unity(12110): AndroidJavaException: java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
08-28 11:45:43.803: E/Unity(12110): java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
08-28 11:45:43.803: E/Unity(12110): 	at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
08-28 11:45:43.803: E/Unity(12110): 	at android.app.BackStackRecord.add(BackStackRecord.java:414)
08-28 11:45:43.803: E/Unity(12110): 	at com.unity3d.player.UnityAndroidPermissions.RequestPermissionAsync(UnityAndroidPermissions.java:66)
08-28 11:45:43.803: E/Unity(12110): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-28 11:45:43.803: E/Unity(12110): 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
08-28 11:45:43.803: E/Unity(12110): 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
08-28 11:45:43.803: E/Unity(12110): 	at android.os.Handler.dispatchMessage(Handler.java:101)
08-28 11:45:43.803: E/Unity(12110): 	at android.os.Looper.loop(Looper.java:164)
08-28 11:45:43.803: E/Unity(12110): 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
08-28 11:45:43.803: E/Unity(12110):   at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in C:\unity\trunk\Runtime\Export\AndroidJNISafe.cs:24 
08-28 11:45:43.803: E/Unity(12110):   at UnityEngine.AndroidJNISafe.CallVoidMethod (IntPtr 

Tried on Pixel XL.

**Comment by Over17** [comment]
Fixed in 825aa68c279dc2caa4e2c97c53b102b76a1b5634.
